# Generated by Django 4.2.11 on 2024-03-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='type',
            field=models.CharField(choices=[('FP', 'Featured product'), ('BS', 'Best seller'), ('NA', 'New arrival')], max_length=4),
        ),
    ]
