# Generated by Django 4.2.11 on 2024-03-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=50),
        ),
    ]
