# Generated by Django 4.2.11 on 2024-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(default='<property object at 0x7cf4e92388b0>', max_length=50),
        ),
    ]
