# Generated by Django 4.2.11 on 2024-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video')], default='IMG', max_length=5),
        ),
    ]
