# Generated by Django 4.2.11 on 2024-04-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productattribute_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
